#
# Table structure for table 'fe_users'
#
CREATE TABLE fe_users (

	tx_qualinetfeuser_vereinsnummer varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_uebungsleiterid varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_kontonr varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_blz varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_bankname varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_mailsvondritten tinyint(1) unsigned DEFAULT '0' NOT NULL,
	tx_qualinetfeuser_bankeinzug tinyint(1) unsigned DEFAULT '0' NOT NULL,
	tx_qualinetfeuser_strasse varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_zusatz varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_strassearbeit varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_gesperrt tinyint(1) unsigned DEFAULT '0' NOT NULL,
	tx_qualinetfeuser_stadtarbeit varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_kontaktnr varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_email2 varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_emailarbeit varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_blsvmitarbeiter tinyint(1) unsigned DEFAULT '0' NOT NULL,
	tx_qualinetfeuser_faxarbeit varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_mobil varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_referentennr varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_pager varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_telprivat varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_telarbeit varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_plzarbeit varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_beschreibung text NOT NULL,
	tx_qualinetfeuser_refvertragversendet tinyint(1) unsigned DEFAULT '0' NOT NULL,
	tx_qualinetfeuser_beschreibungkurz varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_umsatzsteuerid varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_kreditorid varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_durchwahl varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_teilnehmerid varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_iban varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_swift varchar(255) DEFAULT '' NOT NULL,
	tx_qualinetfeuser_blsvwerbung tinyint(1) unsigned DEFAULT '0' NOT NULL,
	tx_qualinetfeuser_ehrenamt tinyint(1) unsigned DEFAULT '0' NOT NULL,
	tx_qualinetfeuser_hauptamt tinyint(1) unsigned DEFAULT '0' NOT NULL,
	tx_qualinetfeuser_datenschutz tinyint(1) unsigned DEFAULT '0' NOT NULL,
	username varchar(255) DEFAULT '' NOT NULL,
	gender int(11) DEFAULT '0' NOT NULL,
	first_name varchar(255) DEFAULT '' NOT NULL,
	last_name varchar(255) DEFAULT '' NOT NULL,
	date_of_birth int(11) DEFAULT '0' NOT NULL,
	email varchar(255) DEFAULT '' NOT NULL,
	address varchar(255) DEFAULT '' NOT NULL,
	city varchar(255) DEFAULT '' NOT NULL,
	zip varchar(255) DEFAULT '' NOT NULL,
	telephone varchar(255) DEFAULT '' NOT NULL,
	fax varchar(255) DEFAULT '' NOT NULL,
	title varchar(255) DEFAULT '' NOT NULL,
	country varchar(255) DEFAULT '' NOT NULL,
	
	company varchar(255) DEFAULT '' NOT NULL,
	www varchar(255) DEFAULT '' NOT NULL,
	ustidben tinyint(1) unsigned DEFAULT '0' NOT NULL,
	ustid varchar(255) DEFAULT '' NOT NULL,
	freigabefahrgemeinschaft tinyint(1) unsigned DEFAULT '0' NOT NULL,
	zustimmungagb tinyint(1) unsigned DEFAULT '0' NOT NULL,
	passbild text NOT NULL,
	checkrichtigkeit tinyint(1) unsigned DEFAULT '0' NOT NULL,
	datumrichtigkeit int(11) DEFAULT '0' NOT NULL,

	tx_extbase_type varchar(255) DEFAULT '0' NOT NULL,

);