<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "qualinet_feuser"
 *
 * Auto generated by Extension Builder 2013-08-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'qualinet_feuser',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Martin Gonschor',
	'author_email' => 'martin.gonschor@blsv.de',
	'author_company' => 'BLSV',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => 'Vereinsmitgliedschaft und Emailwiederholung',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.2.14',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>